[[FlangClassic_RTLib]]
arch = "x86_64"
git-tree-sha1 = "d79b718ae68eeea8a33f50132dfd2f7ade128c1e"
libc = "glibc"
os = "linux"

    [[FlangClassic_RTLib.download]]
    sha256 = "71b7cfd784ee422e10296e2c9424e740934990c54bc10e3585c1d7c4e8e81463"
    url = "https://github.com/JuliaBinaryWrappers/FlangClassic_RTLib_jll.jl/releases/download/FlangClassic_RTLib-v13.0.0+1/FlangClassic_RTLib.v13.0.0.x86_64-linux-gnu.tar.gz"
[[FlangClassic_RTLib]]
arch = "x86_64"
git-tree-sha1 = "8f3d74fe45e41574a103ea1eaa363c9cfa88566a"
libc = "musl"
os = "linux"

    [[FlangClassic_RTLib.download]]
    sha256 = "f3745d27c761408dc2e93302d26213fc71151c419627351c489da6154e956bce"
    url = "https://github.com/JuliaBinaryWrappers/FlangClassic_RTLib_jll.jl/releases/download/FlangClassic_RTLib-v13.0.0+1/FlangClassic_RTLib.v13.0.0.x86_64-linux-musl.tar.gz"
