[[FlangClassic_RTLib]]
arch = "x86_64"
git-tree-sha1 = "02f64180bf0d48f68041cca32b3cf0712233ef47"
libc = "glibc"
os = "linux"

    [[FlangClassic_RTLib.download]]
    sha256 = "4c148fdfa5374e619d6abc08f6dea246a2a1258d3599665fbac5f7bc95354f99"
    url = "https://github.com/JuliaBinaryWrappers/FlangClassic_RTLib_jll.jl/releases/download/FlangClassic_RTLib-v13.0.0+0/FlangClassic_RTLib.v13.0.0.x86_64-linux-gnu.tar.gz"
[[FlangClassic_RTLib]]
arch = "x86_64"
git-tree-sha1 = "455323995a09f58bdcf9ba3d966a4e4c317502e9"
libc = "musl"
os = "linux"

    [[FlangClassic_RTLib.download]]
    sha256 = "bd5161389831cc898b5f97adfff4f7560d24a75aa69ca7bea4753f5c07bc813e"
    url = "https://github.com/JuliaBinaryWrappers/FlangClassic_RTLib_jll.jl/releases/download/FlangClassic_RTLib-v13.0.0+0/FlangClassic_RTLib.v13.0.0.x86_64-linux-musl.tar.gz"
